import React from 'react'
import type { NextPage } from 'next'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'

const ContestTosText = `
**TERMS AND CONDITIONS**

We Can Have Fun by Noun266 Artwork Contest

*Last updated November 22, 2022*

**Noun266-Derived Artwork Contest**

By submitting an entry to this Contest, you (“You” or “Applicant”) hereby agree to be bound by these Terms and Conditions.  You must accept the decisions of the Contest made by Pixel Curators, LLC (“PC”).

1. Eligibility. Applicants must be 18 years of age or older at the time of entry. Proof of age may be required. The Contest is not open to employees of PC or its affiliates, or immediate family and/or household members of such employees.
2. How to Enter. View the clip of the Noun266 NFT (the “Noun266 NFT”) released by PC on Twitter with the hashtag #Noun266Contest and post a derivative artwork related to Noun266 (“Noun266-derived Work”) using the hashtag #Noun266Contest between February 10, 2023, and February 17, 2023. Each Applicant may submit no more than one (1) Noun266-derived Work for this Contest. No receipt will be issued for Your entry.
3. Noun266-derived Work Requirements. The Noun266-derived Work must comply with all of the following requirements:
    1. the Noun266-derived Work shall not show, contain, depict, refer or otherwise allude to the name or logo of any retailer, manufacturer, brand, product, store, place of business, person, company or character;
    2. the Noun266-derived Work shall be Applicant's own original work, created solely by Applicant and not created professionally; shall not have been previously published, released or distributed in any form; shall not have won any award; and
    3. the Noun266-derived Work shall not infringe the copyright, trademark, privacy, publicity, or other personal or proprietary rights of any person or entity, and does not depict any individual who has not granted express written consent to be featured;
    4. the Noun266-derived Work shall not contain, refer or otherwise allude to any material that is violent, lewd, obscene, sexually explicit, pornographic, disparaging, defamatory, libelous, racially or morally offensive, or otherwise contain inappropriate content or objectionable material, as determined by PC;
    5. the Noun266-derived Work shall not promote alcohol, illegal drugs, tobacco, vaping, firearms or weapons (or the use of any of the foregoing), any activities that may appear unsafe or dangerous, or any political agenda or message;
    6. the Noun266-derived Work shall not in any manner defame, misrepresent, contain disparaging remarks or reflect negatively about PC, its products/services, or other people or entities, or in any way reflect negatively upon such parties or explicitly or implicitly communicate messages or images inconsistent with the positive images and/or goodwill with which PC is or wishes to be associated, as determined by PC in its sole discretion;
    7. the Noun266-derived Work shall not contain any personal identification, such as personal names, email addresses or street addresses; and
    8. the Noun266-derived Work shall not depict and shall not itself be in violation of any law.
    
    PC reserves the right to disqualify any Noun266-derived Work that PC determines, in its sole discretion, does not comply with any of these Terms and Conditions or that otherwise contains prohibited or inappropriate content.
    
4. Grant of Rights. Upon posting of a Noun266-derived Work, each Applicant thereby irrevocably grants PC an exclusive, perpetual, worldwide, royalty-free license to use and display the submitted Noun266-derived Work in connection with the Contest and/or other merchandise in any and all media channels or formats existing now or later created. Each Applicant hereby assigns to PC all ownership rights, including copyright rights, to the submitted Noun266-derived Work, and agrees to execute any and all additional documents deemed necessary by PC to effectuate such assignment.
5. Representations and Warranties. Each Applicant represents and warrants that his/her submitted Noun266-derived Work (i) is Applicant’s own original work, (ii) was created solely by Applicant, (iii) has not been previously produced, published, distributed or otherwise exploited, (iv) is not, as of the date of entry, the subject of any actual or threatened litigation or claim, (v) does not violate or infringe the intellectual property rights or other rights of any other person or entity, including, but not limited to, copyright or trademark, and (vi) does not violate any applicable law, regulation, or rule.
6. Indemnification. Applicant hereby agrees to indemnify, defend and hold PC and its parents, subsidiaries, affiliates, agents, employees, officers and directors harmless from and against any and all third-party claims, actions or proceedings of any kind and from any and all damages, liabilities, costs and expenses relating to or arising out of any breach or alleged breach of any of the warranties or representations of Applicant hereunder.
7. Selection of Winners. On or about February 25th, 2023, the Contest judges will select ten (10) prize winners (collectively, “Winners”) based upon the following criteria: (i) the best embodiment or representation of the Noun266 NFT; and (ii) the most creative and skillful representation of the Noun266 NFT. Any tie will be decided by the skill used in producing the Noun266-derived Work. Judges will be qualified through their background and experience to evaluate all submissions using these criteria. The Decisions so made are final. Winners will be notified using the Twitter direct messaging information available.
8. Prize. The ten (10) Winners will receive a real vinyl print of the Noun266 song that is playing in the Noun266 NFT clip. Any Winner’s Noun266-derived Work may be used in future merchandise. Winners are responsible for any applicable federal, state, and local taxes related to receipt of the prize. No transfer, refund, cash redemption, substitution or replacement of the prizes or any part of the prizes is permitted. Prizes may not be exchanged or returned. Winners will not receive any other form of compensation of any kind.
9. Publicity Release. Except where prohibited or restricted by law, a Winner's acceptance of the prize constitutes the Winner’s consent for PC, and any of its affiliates, to use and/or publish the Winner's full name, city and state of residence, photographs or other likenesses, pictures, portraits, video, voice, testimonials, biographical information (in whole or in part), and/or statements made by the Winner regarding the Contest or PC, worldwide and in perpetuity for any and all marketing purposes, including, but not limited to, advertising, trade and/or promotion on behalf of PC, in any and all forms of media, now known or hereafter devised, including, but not limited to, print, TV, radio, electronic, cable, social media, and Internet, without further limitation, restriction, compensation, notice, review, or approval.
10. Use of Personal Information. By entering the Contest, Applicant may be sharing his/her personal information with PC, including, for example, name, address, email address, and telephone number. Personal information collected by PC will be used only for administration of the Contest and awarding prizes. If You are a resident of California, You have the right to request to know what personal information has been collected about You, and to access such information. You also have the right to request deletion of Your personal information, though exceptions under the California Consumer Privacy Act (“CCPA”) may allow PC to retain and use certain personal information notwithstanding Your deletion request. You may send your request for access or deletion by email to info@curated.fund.
11. No Tampering, Right to Cancel, Modify. PC and its parents, subsidiaries, affiliates, agents, employees, officers and directors shall not have any obligation or responsibility, including any responsibility to award any prize to Applicants, with regard to: (a) entries that contain inaccurate information or do not comply with or violate any of the Terms and Conditions; (b) entries, prize claims or notifications that are lost, late, incomplete, illegible, unintelligible, damaged or otherwise not received by PC, in whole or in part, due to computer, human or technical error of any kind; (c) Applicants who have committed fraud or deception in entering the Contest or claiming the prize; (d) malfunctions, failures or difficulties of telephone, electronic, hardware, software, network, Internet or computer; (e) any inability of a Winner to accept the prize for any reason; (f) if a prize cannot be awarded due to delays or interruptions due to Acts of God, natural disasters, terrorism, weather or any other similar event beyond PC’s reasonable control; or (g) any damages, injuries or losses of any kind caused by any prize or resulting from awarding, acceptance, possession, use, misuse, loss or misdirection of any prize or resulting from participating in this Contest or prize related activities. PC reserves the right, in its sole discretion, to disqualify any Applicant it finds to be (a) tampering with the entry process or the operation of the Contest; (b) acting in violation of the Terms and Conditions; or (c) entering or attempting to enter the Contest multiple times through the use of multiple Twitter accounts**,** e-mail addresses, or the use of any robotic or automated devices to post entries. If PC determines, in its sole discretion, that technical difficulties or unforeseen events compromise the integrity or viability of the Contest, PC reserves the right to void the entries at issue, and/or terminate the relevant portion of the Contest, including the entire Contest, and/or modify the Contest, and in case of such termination, award the prizes based upon the criteria set forth hereinabove from all eligible entries received as of the termination date. If the Contest is terminated or modified due to technical difficulties or unforeseen events prior to the expiration date of the entry period, notice will be posted on the @Noun_266 Twitter account.
12. General Release. By participating in the Contest, Applicant hereby releases PC and its parents, subsidiaries, affiliates, agents, employees, officers and directors (the "Released Parties"), from any and all liability, for loss, harm, damage, injury, cost or expense whatsoever, including without limitation, property damage, personal injury (including but not limited to emotional distress), and/or death, which may occur in connection with preparation for, entry or otherwise participation in, the Contest, or possession, acceptance and/or use or misuse of the prize or participation in any Contest-related or prize-related activity and for any claims or causes of action based on publicity rights, defamation or invasion of privacy. The Released Parties assume no responsibility for any injury or damage to Applicant’s or to any other person’s computer, regardless of however caused, relating to or resulting from entering this Contest.
13. Other General Terms. Applicants and winners acknowledge that PC does not make any warranty or representations express or implied, relating to any prize or any part of the Contest. Except where prohibited, all issues concerning the validity, interpretation, and enforceability of these Terms and Conditions, or the rights or obligations of Applicants, Winners, or PC in connection with the Contest, shall be governed by, and construed in accordance with the laws of the State of Delaware, without giving effect to any conflict of law rules. In addition, any dispute relating to the Contest (including these Terms and Conditions) shall be brought in the appropriate federal court having jurisdiction over the subject matter located in Wilmington, Delaware. Applicants and Winners hereby irrevocably consent to the personal jurisdiction of said courts in San Francisco, California, and waive any claim of forum non conveniens or lack of personal jurisdiction.
`

const Contest: NextPage = () => {
  return (
    <div className='bg-white mt-6 w-full'>
    <div className='overflow-scroll text-black max-h-[40rem] md:max-h-[40rem] p-4 leading-10'>
      <ReactMarkdown>
          {ContestTosText}
        </ReactMarkdown>
    </div></div>
  )
}

export default Contest;